services:
  silksplugins-discordbot:
    image: ghcr.io/silksplugins/silksplugins-discordbot:latest
    container_name: silksplugins-discordbot
    restart: unless-stopped
    volumes:
    - silksplugins-discordbot:/data
    networks:
    - silksplugins-discordbot

volumes:
  silksplugins-discordbot:
    external:
      name: silksplugins-discordbot

networks:
  silksplugins-discordbot: {}