// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilKsPlugins.DiscordBot.Databases.RoleReactions;

namespace SilKsPlugins.DiscordBot.Migrations.RoleReactions
{
    [DbContext(typeof(RoleReactionsDbContext))]
    [Migration("20210625120236_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SilKsPlugins.DiscordBot.Databases.RoleReactions.Models.RoleMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId", "ChannelId", "MessageId");

                    b.ToTable("RoleMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
