Token: "CHANGEME"

Commands:
  Prefix: "!"

UserUpdates:
  Reactions:
    Subscribe: "✅"
    Unsubscribe: "❌"
  RoleName: "covid-updates"

Database:
  ConnectionStrings:
    Default: "Server=localhost; Port=3306; Database=silksplugins; User Id=username; Password=password"

Admins:
- "AnExampleAdmin#1234"
