// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilKsPlugins.DiscordBot.Databases.Administration;

namespace SilKsPlugins.DiscordBot.Migrations.Administration
{
    [DbContext(typeof(AdministrationDbContext))]
    [Migration("20210625120524_AddedGuildIdToLogChannel")]
    partial class AddedGuildIdToLogChannel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SilKsPlugins.DiscordBot.Databases.Administration.Models.LogChannel", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("LogChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
