name: Deploy Docker Container

on:
  registry_package:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy Docker container
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: ${{ secrets.DOCKER_REMOTE_HOST }}
        remote_docker_port: ${{ secrets.DOCKER_REMOTE_PORT }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        stack_file_name: compose.yaml
