name: docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate packages token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_PACKAGES_APP_ID }}
          private_key: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: silksplugins/silksplugins-discord-bot:latest
          secrets: |
            "github_token=${{ steps.generate_token.outputs.token }}"
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
